# Generated by Django 5.2.9 on 2025-12-11 03:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Lectores',
            },
        ),
        migrations.AlterModelOptions(
            name='libro',
            options={'verbose_name_plural': 'Libros'},
        ),
        migrations.AddField(
            model_name='autor',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='libro',
            name='copias_disponibles',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField(default=django.utils.timezone.now)),
                ('fecha_devolucion_esperada', models.DateField()),
                ('devuelto', models.BooleanField(default=False)),
                ('lector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.lector')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.libro')),
            ],
            options={
                'verbose_name_plural': 'Préstamos',
                'ordering': ['devuelto', '-fecha_prestamo'],
            },
        ),
    ]
