# Generated by Django 5.2.9 on 2026-01-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_multa'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='paginas',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
