# Generated by Django 5.2.9 on 2026-01-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_libro_paginas'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='portada_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
