# Generated by Django 5.2.9 on 2026-01-28 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_libro_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='estante',
            field=models.CharField(blank=True, help_text='Ej: Pasillo A, Estante 3', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='notas_entrega',
            field=models.TextField(blank=True, help_text='Estado del libro al entregarlo', null=True),
        ),
    ]
